# Site settings
title: tech by saurav
email: hashincludesoftwarelabs@gmail.com
description: "Musings of a curious techie."
baseurl: ""
url: "http://hashincludelabs.github.io"
twitter_username: hashincludelabs
github_username:  hashincludelabs

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge