# Site settings
title: tech by saurav
email: 
description: "Musings of a curious techie."
baseurl: ""
url: "http://sauravfyi.github.io"
twitter_username: sauravfyi
github_username:  sauravfyi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge