# Site settings
title: "boring software"
name: Saurav Dey
email: 
description: "AI, tech and other boring stuff."
baseurl: ""
url: "http://boringsoftwarefyi.github.io"
twitter_username: sauravfyi
github_username:  boringsoftwarefyi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
