# Site settings
title: tensorbeing
email: tensorbeing@gmail.com
description: "Musings of a curious techie."
baseurl: ""
url: "http://tensorbeing.github.io"
twitter_username: tensorbeing
github_username:  tensorbeing

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge