# Site settings
title: "hashinclude!"
name: Saurav Dey
email: 
description: "AI, tech and other boring stuff."
baseurl: ""
url: "http://hashincludelabs.github.io"
twitter_username: hashincludelabs
github_username:  hashincludelabs

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge